----ALTER,drop,truncate,delete,upadate

create database jntu;
use jntu;
create table students(ID VARCHAR(255) PRIMARY KEY, NAME CHAR(50), COURSE CHAR(50));
SELECT * FROM STUDENTS;
CREATE TABLE COURSES(COURSEID VARCHAR(255),BRANCH CHAR(50));
INSERT INTO COURSES VALUES ("C01" ,"AIML"),
("C02" ,"DS"),
("C03" ,"CSE"),
("C04" ,"IT"),
("C05" ,"ECE"),
("C06" ,"EEE");
ALTER TABLE COURSES ADD COLUMN PROFESSOR CHAR(50);
ALTER TABLE COURSES MODIFY BRANCH VARCHAR(255);
ALTER TABLE COURSES DROP PROFESSOR;
ALTER TABLE COURSES RENAME COLUMN BRANCH TO COURSE;
SELECT * FROM COURSES;
DROP TABLE STUDENTS;
TRUNCATE TABLE COURSES;
INSERT INTO STUDENTS VALUES ("J01","DEEPIKA","AIML"), 
("J02","RAJ","CSE"),
("J03","LAXMI","DS"),
("J04","DIVYA","ECE"),
("J05","PRIYANSHI","CIVIL"),
("J06","RAGHU","EEE");
UPDATE STUDENTS SET  COURSE = "AIML" WHERE ID="J03";
DELETE FROM STUDENTS WHERE ID = "J04";











